### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by liudonghua123** [xuan525/Bili-dl#5]
I start to download some videos, and after a while, it crashed with the following errors.

![image](https://user-images.githubusercontent.com/2276718/110274275-63a8cd00-8009-11eb-91f6-b88d8872380d.png)

![image](https://user-images.githubusercontent.com/2276718/110271282-a4e9ae80-8002-11eb-90b8-db733a99cc49.png)

It seemed to have some problems with the length of the path.

**Comment by liudonghua123** [comment]
I searched the Internet and found some useful links https://docs.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation, https://docs.microsoft.com/zh-cn/windows/win32/sbscs/application-manifests#longpathaware, https://docs.microsoft.com/zh-cn/windows/win32/fileio/naming-a-file#maximum-path-length-limitation, https://docs.microsoft.com/en-us/dotnet/api/system.io.pathtoolongexception?view=net-5.0, https://stackoverflow.com/questions/8745215/best-way-to-resolve-file-path-too-long-exception.

Maybe I can fix it with one of the following methods:
1. Enable `LongPathsEnabled` in Regedit and include the `longPathAware` element in the application manifest.
  ```reg
  Windows Registry Editor Version 5.00
  
  [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
  "LongPathsEnabled"=dword:00000001
  ```

  ```xml
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
      <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
          <ws2:longPathAware>true</ws2:longPathAware>
      </windowsSettings>
  </application>
  ```

2. Use no MAX_PATH restrictions functions like `GetFullPathNameW` instead of `GetFullPathName`

**Comment by Abc373** [comment]
我感觉安装的时候配置错误了，systemIO感觉跟机器有关，不知道瑄佬怎么看

**Comment by xuan25** [comment]
Sorry for the late reply. I was busy with my dissertation.

Thank you for the useful links. I have found that removing the name length restriction is limited to Windows 10 version 1607 or higher. I wonder if truncating the filename would be a better option for compatibility reasons rather than lifting the restriction. Also, I'm not sure if files with filenames that exceed the limit will be accessible properly on older systems.
